name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.actor == 'gertzgal'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cli/gh-extension-precompile@v2
        with:
          go_version_file: go.mod
          generate_attestations: true
          build_script_override: script/build.sh
